# Generated by Django 3.1 on 2020-08-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silic', '0002_auto_20200811_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band_details',
            name='Discount_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='band_details',
            name='Maximum_quantity',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='band_details',
            name='Minimum_quantity',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='band_details',
            name='Size_in_inch',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='band_details',
            name='Unit_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='band_order',
            name='Order_date',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='band_order',
            name='Pincode',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='band_order',
            name='Pricee',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='band_order',
            name='Quantitty',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='band_order',
            name='Totall_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='registration',
            name='About',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='registration',
            name='City',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Lock',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Phone',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Pincode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registration',
            name='State',
            field=models.CharField(default='', max_length=200),
        ),
    ]
