# Generated by Django 3.1 on 2020-08-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silic', '0003_auto_20200812_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='User_role',
            field=models.CharField(default='', max_length=200),
        ),
    ]
