# Generated by Django 3.1 on 2020-08-19 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silic', '0007_auto_20200819_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silic.size')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='silic.price'),
        ),
    ]
