# Generated by Django 3.1 on 2020-08-20 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silic', '0008_auto_20200819_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fontstyle',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='silic.category'),
        ),
    ]
