# Generated by Django 3.1 on 2020-08-20 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silic', '0009_auto_20200820_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='silic.size'),
        ),
        migrations.AlterField(
            model_name='size',
            name='fontstyle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='silic.fontstyle'),
        ),
    ]
