# Generated by Django 3.1 on 2020-08-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silic', '0011_auto_20200821_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conveyance_fees',
            name='Delivery_charge_max_km',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='conveyance_fees',
            name='Delivery_charge_min_km',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='conveyance_fees',
            name='Delivery_fees',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='conveyance_fees',
            name='Shipping_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='conveyance_fees',
            name='Shipping_days',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='conveyance_fees',
            name='Shipping_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='conveyance_fees',
            name='Status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
