# Generated by Django 3.1 on 2020-09-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silic', '0013_auto_20200827_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='Answer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='Customer_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='Customer_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='Question',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='Submission_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
