# Generated by Django 3.1 on 2020-09-01 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silic', '0014_auto_20200901_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='catt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='silic.category_product'),
        ),
    ]
