# Generated by Django 3.1 on 2020-09-02 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silic', '0015_auto_20200901_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust_cart',
            name='Delivery_charge',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cust_cart',
            name='Pricce',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cust_cart',
            name='Total_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cust_cart',
            name='regg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='silic.registration'),
        ),
    ]
