# Generated by Django 3.1 on 2020-09-15 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silic', '0016_auto_20200902_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band_details',
            name='Size_in_inch',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cust_cart',
            name='regg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silic.registration'),
            preserve_default=False,
        ),
    ]
